name: Deploy to ECR

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    environment: produccion

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Download Models from S3
        run: |
          mkdir -p entrenamiento_kaggle/work_dirs
          echo "Descargando modelos desde S3 Express (Filtros selectivos)..."
          # S3 Express One Zone: Usamos cp recursivo con filtros para bajar SOLO pesos y configs.
          # Esto bajará los .pth aunque estén en subcarpetas, pero ignorará logs y temporales.
          aws s3 cp s3://golfpose-gpu-kaggel--use1-az4--x-s3/work_dirs/ entrenamiento_kaggle/work_dirs/ \
            --recursive \
            --exclude "*" \
            --include "*.pth" \
            --include "*.bin" \
            --include "*.py" \
            --include "*last_checkpoint*"

          echo "Verificación de archivos descargados:"
          find entrenamiento_kaggle/work_dirs/ -maxdepth 3 -not -path '*/.*'
          du -sh entrenamiento_kaggle/work_dirs/*

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: golfpose-gpu
          IMAGE_TAG: latest
        run: |
          # Build the docker container and push it to ECR
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
